name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up private key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh-keyscan -p 22 ${{ secrets.PUBLIC_KEY }} >> known_hosts

      - name: Access server
        run: ssh -p ${{ secrets.WEBSITE_PORT }} -i id_rsa ${{ secrets.WEBSITE_USERNAME_IP }}

      - name: Update files
        run: git pull

      - name: Log off
        run: exit
