name: Deploy

on:
  push:
    branches:
      - main
      - automatic-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          cd ~/.ssh/
          echo "${{ secrets.PRIVATE_KEY }}" > id_rsa
          echo "${{ secrets.PUBLIC_KEY }}" > id_rsa.pub
          chmod 600 id_rsa
          chmod 600 id_rsa.pub
          ssh-keyscan -H -p ${{ secrets.WEBSITE_PORT }} ${{ secrets.WEBSITE_IP }} >> known_hosts
          sudo apt-get install sshpass

      - name: Access server
        run: |
          ssh -T -o StrictHostKeyChecking=no -p ${{ secrets.WEBSITE_PORT }} -i ~/.ssh/id_rsa ${{ secrets.WEBSITE_USERNAME }}@${{ secrets.WEBSITE_IP }} uptime

      - name: Sleep for 10 seconds
        run: sleep 30s

      - name: Enter SSH passphrase
        run: echo ${{ secrets.SSH_PASSPHRASE }}

      - name: Update files
        run: git pull

      - name: Log off
        run: exit
