name: Deploy

on:
  push:
    branches:
      - main
      - automatic-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up private key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Access server
        run: |
          ssh -T -p ${{ secrets.WEBSITE_PORT }} -i id_rsa ${{ secrets.WEBSITE_USERNAME_IP }}
          echo ${{ secrets.SSH_PASSPHRASE }}

      - name: Update files
        run: git pull

      - name: Log off
        run: exit
